/*
    BKG_APARTMENT_LAMP_BOT_TILES.H
    File generated by gb_map_converter.
*/
#pragma once

#define BKG_APARTMENT_LAMP_BOT_TILE_COUNT 4

extern const unsigned char bkg_apartment_lamp_bot_tiles[64];
