/*
    BKG_APARTMENT_LAMP_MAP.H
    File generated by gb_map_converter.
*/
#pragma once

#define BKG_APARTMENT_LAMP_MAP_WIDTH 4
#define BKG_APARTMENT_LAMP_MAP_HEIGHT 2

extern const unsigned char bkg_apartment_lamp_map[];
