/*
    BKG_APARTMENT_LAMP_TOP_TILES.H
    File generated by gb_map_converter.
*/
#pragma once

#define BKG_APARTMENT_LAMP_TOP_TILE_COUNT 4

extern const unsigned char bkg_apartment_lamp_top_tiles[64];
