/*
    BKG_APARTMENT_LAMP_TOP_MAP.H
    File generated by gb_map_converter.
*/
#pragma once

#define BKG_APARTMENT_LAMP_TOP_MAP_WIDTH 4
#define BKG_APARTMENT_LAMP_TOP_MAP_HEIGHT 1

extern const unsigned char bkg_apartment_lamp_top_map[];
