/*
    BKG_APARTMENT_MAP.H
    File generated by gb_map_converter.
*/
#pragma once

#define BKG_APARTMENT_MAP_WIDTH 20
#define BKG_APARTMENT_MAP_HEIGHT 18

extern const unsigned char bkg_apartment_map[];
