/*
    BKG_APARTMENT_SCROLL_MAP.H
    File generated by gb_map_converter.
*/
#pragma once

#define BKG_APARTMENT_SCROLL_MAP_WIDTH 32
#define BKG_APARTMENT_SCROLL_MAP_HEIGHT 32

extern const unsigned char bkg_apartment_scroll_map[];
