/*

 APARTMENT_SMOKE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define apartment_smokeBank 0
/* Start of tile array. */
extern unsigned char apartment_smoke[];
#define apartment_smokeLen 1

/* End of APARTMENT_SMOKE.H */
