/*

 BKG_APARTMENT_LAMP_TOP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define apartment_lamp_topBank 0
/* Start of tile array. */
extern unsigned char apartment_lamp_top[];
#define apartment_lamp_topLen 4

/* End of BKG_APARTMENT_LAMP_TOP.H */
