//AUTOGENERATED FILE FROM png2mtspr
#define cig_shine_TILE_H 8
#define cig_shine_WIDTH 16
#define cig_shine_HEIGHT 16
#define cig_shine_PIVOT_X 8
#define cig_shine_PIVOT_Y 8

extern const UINT8 cig_shine_data[128];
extern const metasprite_t* const cig_shine_metasprites[12];
