//AUTOGENERATED FILE FROM png2mtspr
#define smoke_TILE_H 8
#define smoke_WIDTH 16
#define smoke_HEIGHT 16
#define smoke_PIVOT_X 8
#define smoke_PIVOT_Y 8

extern const UINT8 smoke_data[192];
extern const metasprite_t *const smoke_metasprites[12];
