//AUTOGENERATED FILE FROM png2mtspr
#define tile_detectivewalk_TILE_H 8
#define tile_detectivewalk_WIDTH 16
#define tile_detectivewalk_HEIGHT 16
#define tile_detectivewalk_PIVOT_X 8
#define tile_detectivewalk_PIVOT_Y 8

extern const UINT8 tile_detectivewalk_data[384];
extern const metasprite_t* const tile_detectivewalk_metasprites[12];
